Question 1)Creating an array and printing its dtype

In [ ]:
import numpy as np
l=[1,2,3,4]
arr=np.array(l)
arr.dtype

dtype('int64')

Question 2)Checking the data type of an array

In [ ]:
arr=np.array([1.5,2.6,3.7])
print(arr.dtype)

float64


Question 3)crating an array of complex datatype

In [ ]:
arr=np.array([1+3j,2+4j,5+6j],dtype='complex128')
arr

array([1.+3.j, 2.+4.j, 5.+6.j])

Question 4)converting the data type of array

In [ ]:
arr=np.array([1.5,2.6,3.7],dtype='complex128')
print(arr)

[1.5+0.j 2.6+0.j 3.7+0.j]


Question 5)reducing the precision by changing the data type

In [ ]:
import numpy as np
arr=np.array([1.555666666666666666666666,2.634,3.734],dtype='float64')
arr.nbytes
print(type(arr))
print(arr,end='\n')
arr.astype('float32')
print(arr)
arr.shape
arr2=np.array([[1,2,3]])
arr2.ndim

<class 'numpy.ndarray'>
[1.55566667 2.634      3.734     ]
[1.55566667 2.634      3.734     ]


2

Question 7) creating function that takes array as attribute and returns dimension of array

In [ ]:
def dimension(a):
  return a.ndim
dimension(arr2)


2

Question 6) creating function that takes array as attribute and returns shape ,size,type of array

In [ ]:
def array_attribute(a):
  l=[a.shape,a.size,a.dtype]
  return l
array_attribute(arr2)


[(1, 3), 3, dtype('int64')]

Question 8)function to find item size and toatal bytes

In [ ]:
def array_item(a):
  l=[a.itemsize,a.nbytes]
  return l
array_item(arr2)

[8, 24]

Question 9)

In [ ]:
def array_stride(a):
  return a.nbytes//a.itemsize
array_stride(arr)

3

Question 10)this question is same as above question the extra it returns the size

Question 11) Creating an zero array of size n

In [ ]:
import numpy as np
def create_zero_array(n):
  k=np.zeros(n)
  return k
create_zero_array(5)

array([0., 0., 0., 0., 0.])

Question 12) creating a matrix of ones

In [ ]:
def create_matrix_ones(m,n):
  k=np.ones((m,n))
  return k
create_matrix_ones(2,3)


array([[1., 1., 1.],
       [1., 1., 1.]])

Question 13)generating an array with certain range

In [ ]:
def genarating_range_array(start,stop,step):
  k=np.arange(start,stop,step)
  return k
genarating_range_array(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

question 14)genarating linear spaced array

In [ ]:
def genarating_linear_array(start,end):
  k=np.linspace(start,end)
  return k
genarating_linear_array(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

Question 15)creating identity matrix

In [ ]:
def create_identity_matrix(n):
  k=np.identity(n)
  return k
create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Question 16)python list to array

In [ ]:
def list_array(l):
  k=np.array(l)
  return k
list_array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

Question 17)Demonstrating the use of numpy.view()

In [ ]:
l=np.array([1,2,3,4,5])
v=np.ndarray.view(l)
l+=1
print(l,v)

[2 3 4 5 6] [2 3 4 5 6]


Question 18)concatination of 2 array along specified axis

In [ ]:
import numpy as np

def concat(arr1, arr2):
    # Concatenate along columns (axis=1)
    k1 = np.concatenate((arr1, arr2), axis=1)
    return k1

# Example with compatible shapes for axis=1 concatenation
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])  # Shape (4, 2)
arr2 = np.array([[5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])  # Shape (4, 4)

print(concat(arr1, arr2))



[[ 1  2  5  6  7  8]
 [ 3  4  9 10 11 12]
 [ 5  6 13 14 15 16]
 [ 7  8 17 18 19 20]]


In [ ]:
import numpy as np

def concat(arr1, arr2):
    # Concatenate along rows (axis=0)
    k1 = np.concatenate((arr1, arr2), axis=0)
    return k1

print(concat(np.array([[1, 2], [3, 4], [5, 6], [7, 8]]), np.array([[5, 6], [7, 8], [9, 10], [11, 12]])))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


Question 19)concatinate horizontaly means concatinating along axis=1 which is done in the above example

Question 21)function using numpy to create an array of integers with in specified range

In [ ]:
import numpy as np
def array(start,end,step):
  k=np.arange(start,end+step,step)
  return k
array(2,10,2)

array([ 2,  4,  6,  8, 10])

Question 22) generating an array between 0 and 1

In [ ]:

def array(start,end,value):
  k=np.linspace(start,end,value)
  return k
array(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Question 23) generating an array of logarithmically spaced

In [ ]:
import numpy as np
def array(start,end):
  k=np.logspace(start,end)
  return k
array(0,2)

array([  1.        ,   1.09854114,   1.20679264,   1.32571137,
         1.45634848,   1.59985872,   1.75751062,   1.93069773,
         2.12095089,   2.32995181,   2.55954792,   2.8117687 ,
         3.0888436 ,   3.39322177,   3.72759372,   4.09491506,
         4.49843267,   4.94171336,   5.42867544,   5.96362332,
         6.55128557,   7.19685673,   7.90604321,   8.68511374,
         9.54095476,  10.48113134,  11.51395399,  12.64855217,
        13.89495494,  15.26417967,  16.76832937,  18.42069969,
        20.23589648,  22.22996483,  24.42053095,  26.82695795,
        29.47051703,  32.37457543,  35.56480306,  39.06939937,
        42.9193426 ,  47.14866363,  51.79474679,  56.89866029,
        62.50551925,  68.6648845 ,  75.43120063,  82.86427729,
        91.0298178 , 100.        ])

24) creating pandas datastructure

In [ ]:
import pandas as pd
arr
arr=np.random.randint(0,100,size=(5,3))
df=pd.DataFrame(arr)
df

0   1   2
0   6  67  68
1  86  18  47
2  32  37  82
3  57  26  67
4  19  89   3

25) makes changes in the specific column of dataframe

In [ ]:
df[0].np

AttributeError: 'Series' object has no attribute 'np'

26) accessing the elements of the array

In [ ]:
arr=np.array([10,20,30,40,50])
arr[2]

30

27) accessing the elements of the 2D array


In [ ]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr_2d[1][2]

6

28)using boolean indexing

In [ ]:
arr=np.array([3,8,2,10,5,7])
arr[arr>5]

array([ 8, 10,  7])

29)index slicing

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[2:6]

array([3, 4, 5, 6])

30)slicing of 2D array

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]


array([[2, 3],
       [5, 6]])

31) numpy function to extract elements in specific order from 2D array

In [ ]:
import numpy as np
l=[[1,2],[3,2],[2,1]]
arr=np.array(l)
def twod_array(a,b):
  for i in b:
    print(a[i[0]][i[1]])

array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
twod_array(array_2d,arr)


6
12
8


32)numpy function to filter elments using boolean indexing

In [ ]:
def filter(num,arr):
     return arr[arr>num]

filter(1,np.array([1,2,3,4]))

array([2, 3, 4])

33)numpy function to extract elements in specific order from 3D array

In [ ]:
def threed_array(a,b,c,d):
  for i in range(len(b)):
    print(a[b[i]][c[i]][d[i]])
a=np.array([0,0,0])
b=np.array([0,2,0])
c=np.array([0,1,1])
array_3d=np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]]])
threed_array(array_3d,a,b,c)

1
8
2


34)numpy function to filter elments using boolean indexing

In [ ]:
def filter(num,arr):
     return arr[np.logical_and(arr>num,arr%2==0)]

filter(1,np.array([1,2,3,4]))

array([2, 4])

35) extracting exlements from 2d array using row and column indices provided by separate arrays is solved above

36)adding scalar element to matrix

In [ ]:
array_2d=np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
array_2d+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

37)numpy broadcasting

In [ ]:
arr1=np.array([[1,2,3]])
arr2=np.array([[1,2,3,10],
               [4,5,6,11],
               [7,8,9,12]])
arr1*arr2.T

array([[ 1,  8, 21],
       [ 2, 10, 24],
       [ 3, 12, 27],
       [10, 22, 36]])

38)

In [ ]:
arr1+arr2.T

array([[ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12],
       [11, 13, 15]])

39)broadcasting

In [ ]:
arr1=np.array([[1],
      [2],
      [3]])
arr2=np.array([[1,2,3]])
arr1+arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

40) broadcasting

In [ ]:
import numpy as np

# Define the arrays
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # Shape (2, 3)

arr2 = np.array([
    [7, 8],
    [9, 10]
])  # Shape (2, 2)

# Repeat or tile arr2 to match arr1's shape
# We reshape arr2 to (2, 1) and broadcast it to (2, 3)
arr2_expanded = np.repeat(arr2, 3, axis=1)
arr1=np.repeat(arr1,2,axis=1)

# Element-wise multiplication
result = arr1 * arr2_expanded

print(result)



[[ 7  7 14 16 24 24]
 [36 36 45 50 60 60]]


Question 41) calculating column wise mean

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr[0:2,0].mean()
# np.shape(arr)[0]
def column_mean(a):
  for i in range(np.size(a[0])):
    print(f"column {i} average=",{a[0:np.shape(a)[0],i].mean()})
column_mean(arr)

column 0 average= {2.5}
column 1 average= {3.5}
column 2 average= {4.5}


Question 42) finding maximun in each row

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0].max()
def row_max(a):
  for i in range(np.shape(a)[0]):
    print(a[i].max())
row_max(arr)

3
6


Question 43)finding the indices of max value in each column

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
def column_max(a):
  for i in range(np.size(a[0])):
    print(f"column {i} average=",{a[0:np.shape(a)[0],i].max()})
column_mean(arr)

Question 44)

Question 45) checking if all the elemnets in the row are even

In [ ]:
import numpy as np
arr=np.array([[2,4,6],[3,5,7]])
for i in range(np.shape(arr)[1]):
  flag=True
  for j in range(np.shape(arr)[0]):
    if(arr[j][i]%2!=0):
      flag=False
      break
  if(flag==False):
    print(f"the column {i} is not even ")
  else:
    print(f"the column {i} even")


the column 0 is not even 
the column 1 is not even 
the column 2 is not even 


Question 46)reshaping a matrix

In [ ]:
arr=np.array([1,2,3,4,5,6])
np.reshape(arr,(2,3))
np.reshape(arr,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

Question 47)function that return s flattened array

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
def flat(a):
  return a.flatten()
flat(arr)

array([1, 2, 3, 4, 5, 6])

Question 48) concatination of 2 arrays along certain axis

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def concat(a,b,c):
  return np.concatenate((a,b),axis=c)
concat(array1,array2,1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Question 49)splitting of an array

In [ ]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(arr,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

Question 50) modification of array

In [ ]:
import numpy as np

def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    array_with_inserts = np.insert(original_array, indices_to_insert, values_to_insert)
    final_array = np.delete(array_with_inserts, indices_to_delete)
    return final_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Final array:", result)


Final array: [ 1 10  4 11  5]


Question 51)

In [ ]:
arr1=np.array([1,5,7,3,8,9,4,6,3,2])
arr2=np.arange(1,11)
arr1+arr2

array([ 2,  7, 10,  7, 13, 15, 11, 14, 12, 12])

Question 52)

In [ ]:
arr1=np.linspace(10,1,10,dtype=int)
arr2=np.linspace(1,10,10,dtype=int)
arr1-arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

Question 53)

In [ ]:
arr1=np.random.randint(0,100,size=5)
arr2=np.linspace(1,5,5,dtype=int)
arr1*arr2

array([ 91,  76, 213,  68, 290])

Question 54)

In [ ]:
import numpy as np
arr1=np.linspace(2,10,5,dtype=int)
arr2=np.linspace(1,5,5,dtype=int)
arr1/arr2

array([2., 2., 2., 2., 2.])

Question 55)

In [ ]:
arr1=np.linspace(1,5,5,dtype=float)
arr2=np.linspace(5,1,5,dtype=float)
np.power(arr1,arr2)

array([ 1., 16., 27., 16.,  5.])

Question 56)

In [ ]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count(a):
  cnt=0
  for i in range(len(arr)):
    if(arr[i]==a):
      cnt=cnt+1
  return cnt
count('world')


1

Question 57)

In [ ]:
import numpy as np

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract(arr):
    l = []  # Initialize the list to store uppercase characters
    for i in arr:
        for j in i:
            if j.isupper():  # Use str.isupper() to check if a character is uppercase
                l.append(j)
    return l

# Call the function
result = extract(arr)
print(result)



['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


Question 59)

In [ ]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
l=""
for i in range(len(arr1)):
  l=l+arr1[i]+" "
  l=l+arr2[i]+" "
print(l)

Hello Open World AI 


Question 60)

In [ ]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
s=""
for i in arr:
  if len(i)>=len(s):
    s=i
print(i)

pineapple


Question 61)

In [ ]:
import numpy as np
import pandas as pd
arr1=np.random.randint(1,1000,size=100)
df=pd.DataFrame(arr1)

In [ ]:
df.describe()

0
count  100.000000
mean   540.960000
std    289.403633
min      3.000000
25%    287.750000
50%    528.000000
75%    819.250000
max    990.000000

from matplotlib import pyplot as plt
_df_0[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

Question 62 is same as 61

Question 63)

In [ ]:
arr1=np.array([1,2,3,4,5,8])
arr2=np.array([10,45,35,56,71,81])
np.corrcoef(arr1,arr2)

array([[1.       , 0.9098429],
       [0.9098429, 1.       ]])

Question 64)

In [ ]:
import numpy as np
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(m1,m2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

Question 65)

In [ ]:
arr1=np.random.randint(10,1000,size=50)
np.percentile(arr1,[10,50,90])

array([104.4, 527.5, 861. ])

In [ ]:
np.quantile(arr1,[0.25,0.75])

array([197.5 , 741.25])

In [ ]:
arr1

array([212, 165, 538, 743,  90, 819, 734, 803, 403, 407, 541, 115, 764,
       438, 871, 219, 264, 992, 860, 560, 697, 736, 303, 579, 621, 199,
       106, 650, 870, 947, 219, 801, 197, 121, 633, 517,  11, 826,  13,
        19, 413, 588, 158, 182, 132, 876, 551,  64, 509, 850])

Question 66)

In [ ]:
print(np.where(arr1==121))

(array([33]),)


Question 67)

In [ ]:
arr1=np.random.randint(10,1000,size=50)
np.sort(arr1)

array([ 45,  73, 100, 101, 117, 119, 126, 156, 170, 182, 182, 188, 205,
       210, 241, 251, 254, 257, 257, 258, 280, 286, 329, 345, 383, 395,
       415, 418, 435, 458, 462, 517, 546, 560, 567, 596, 675, 710, 716,
       723, 757, 760, 827, 846, 852, 878, 906, 913, 913, 995])

Question 68)

In [ ]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

Question 69)

In [ ]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

Question 70)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
# arr[(arr[arr>=20])>=40]
arr1=arr[arr>=20]
arr1[arr1<=40]

array([20, 30, 40])

Question 71)

In [ ]:
array = np.array([1, 2, 3], dtype=np.int32)
array.dtype.byteorder


'='

Question 72)

In [ ]:
array = np.array([1, 2, 3], dtype=np.int32)
array.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

Question 73)

In [ ]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

Question 76)

In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
copy_arr=arr1
copy_arr[0]=10
arr1
#shallow copy

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Question 77)

In [11]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
slice_view=matrix[0:2]
slice_view[1][0]=5
matrix

array([[1, 2, 3],
       [5, 5, 6],
       [7, 8, 9]])

Question 78)

In [15]:
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
slice_view=matrix[0:2]
slice_view=slice_view+5
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Question 79)

In [19]:
matrix=np.array([[1,2],[3,4],[5,6],[7,8]])
reshaped=np.reshape(matrix,newshape=(4,2))
reshaped[0][1]=10
matrix

array([[ 1, 10],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]])

Question 80)

In [23]:
data=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
data_copy=data[data>5]
data_copy[0]=1
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Question 81)

In [24]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[10,9,8],[7,6,5],[4,3,2]])
print(matrix1+matrix2)
print(matrix1-matrix2)

[[11 11 11]
 [11 11 11]
 [11 11 11]]
[[-9 -7 -5]
 [-3 -1  1]
 [ 3  5  7]]


Question 82)

In [27]:
c=np.array([[1,2],[4,5],[7,8]])
d=np.array([[1,2,3,4],[3,4,6,7]])
np.dot(c,d)

array([[ 7, 10, 15, 18],
       [19, 28, 42, 51],
       [31, 46, 69, 84]])

Question 83)

In [28]:
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.transpose(matrix1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Question 84)

In [30]:
matrix1=np.array([[1,2,4],[4,5,6],[7,8,9]])
np.linalg.det(matrix1)

-2.9999999999999996

Question 85)

In [33]:
matrix1=np.array([[1,2,4],[4,5,6],[7,8,9]])
np.linalg.inv(matrix1)

array([[ 1.        , -4.66666667,  2.66666667],
       [-2.        ,  6.33333333, -3.33333333],
       [ 1.        , -2.        ,  1.        ]])